### ISSUE TITLE
Slllllow org mode

### ISSUE THREAD

**Issue by andrewsanchez** [sachac/.emacs.d#10]
Trying to open your file in org-mode caused a super slow org-mode buffer for me.  This was not the case when opening with `emacs -q`

Adding this line to your file fixed the lag issue, allowing me to brows your file without needing to open with `emacs -q`:
`#+STARTUP: showeverything`

Any ideas for a better solution?  I don't use org-bullets, the disabling of which was suggested as a solution here:  https://stackoverflow.com/questions/40793325/emacs-diagnosis-org-mode-unbearably-slow-and-often-stalls

Removing `(setq org-hide-leading-stars t)` from my config also had no impact.  I do use `org-pomodoro`  Here is the org related section of my init.el:

```emacs-lisp
  (use-package org
    :load-path "~/.emacs.d/packages/org-mode/lisp"
    :config
    (setq org-hide-leading-stars t)
    (setq org-default-notes-file "/Users/andrew/org/notes.org")
    (setq org-capture-templates
	  '(
	    ("t" "TODO" entry (file+headline "/Users/andrew/org/gtd.org" "Tasks")
	    "* TODO %? \n%U\n" :empty-lines 1)
	    ("j" "Journal" entry (file+datetree "/Users/andrew/org/journal.org")
	    "* %?\nEntered on %U\n")
	    ("n" "Note" entry (file+headline "/Users/andrew/org/notes.org" "Notes")
	    "* %i\n")))
    (setq org-refile-targets '((nil :maxlevel . 3)
			       (org-agenda-files :maxlevel . 3)))
    (setq org-outline-path-complete-in-steps nil)
    (setq org-refile-allow-creating-parent-nodes 'confirm)
    (setq org-src-fontify-natively t)
    (setq org-agenda-files '("/Users/andrew/org/gtd.org"))
    (setq org-agenda-custom-commands
	  '(("w" "work" tags-todo "TODO=\"TODO\"+category=\"pmi\"")))
```

**Comment by sachac** [comment]
Hmm, it could be that Org is generally slow at parsing large Org files
(especially with lots of source blocks) for visibility information, which
is why I set org-startup-folded to nil myself. I'll add the showeverything
directive to the file next time I'm at my computer. Thanks for your
patience!

On Aug 2, 2017 8:07 AM, "Andrew Sanchez" <notifications@github.com> wrote:

Trying to open your file in org-mode caused a super slow org-mode buffer
for me. This was not the case when opening with emacs -q

Adding this line to your file fixed the lag issue, allowing me to brows
your file without needing to open with emacs -q:
#+STARTUP: showeverything

Any ideas for a better solution? I don't use org-bullets, the disabling of
which was suggested as a solution here: https://stackoverflow.com/
questions/40793325/emacs-diagnosis-org-mode-unbearably-slow-and-often-stalls

Removing (setq org-hide-leading-stars t) from my config also had no impact.
I do use org-pomodoro Here is the org related section of my init.el:

  (use-package org
    :load-path "~/.emacs.d/packages/org-mode/lisp"
    :config
    (setq org-hide-leading-stars t)
    (setq org-default-notes-file "/Users/andrew/org/notes.org")
    (setq org-capture-templates
	  '(
	    ("t" "TODO" entry (file+headline "/Users/andrew/org/gtd.org" "Tasks")
	    "* TODO %? \n%U\n" :empty-lines 1)
	    ("j" "Journal" entry (file+datetree "/Users/andrew/org/journal.org")
	    "* %?\nEntered on %U\n")
	    ("n" "Note" entry (file+headline "/Users/andrew/org/notes.org" "Notes")
	    "* %i\n")))
    (setq org-refile-targets '((nil :maxlevel . 3)
			       (org-agenda-files :maxlevel . 3)))
    (setq org-outline-path-complete-in-steps nil)
    (setq org-refile-allow-creating-parent-nodes 'confirm)
    (setq org-src-fontify-natively t)
    (setq org-agenda-files '("/Users/andrew/org/gtd.org"))
    (setq org-agenda-custom-commands
	  '(("w" "work" tags-todo "TODO=\"TODO\"+category=\"pmi\"")))

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sachac/.emacs.d/issues/10>, or mute the thread
