### ISSUE TITLE
babel language identifier: R instead of r 

### ISSUE THREAD

**Issue by yitang** [sachac/.emacs.d#2]
Hi Sacha,

Your css style sheet looks really good and I want to set it as default for exported html.  But I have a problem with `src R` block, it will shows nothing, it takes me a while to figure out that `src r` works fine.  

I am not sure how the css works or how much effort to change from _r_ to _R_ in your style sheet, but shall we stick to the [official language identifier](http://orgmode.org/worg/org-contrib/babel/languages.html)? 

Yi

**Comment by sachac** [comment]
Hi, Yi! I'm not entirely sure what you mean.
http://pages.sachachua.com/evil-plans/quest.html has some #begin_src R
blocks that display if I use :exports both or :exports code. Is it because
when you have #+begin_src R, it's trying to export an image? I don't think
I have anything specifically in my CSS for R... Could you please reply with
more details? Thanks!

**Comment by yitang** [comment]
Hi Sacha,

You are right, your CSS has no problem and looks good.  I made some mistakes when mixing the CSS files.  Please close this issue.

Yi
