### ISSUE TITLE
link hygiene

### ISSUE THREAD

**Issue by TomRoche** [sachac/.emacs.d#8]
Just a reminder that [_sic transit gloria webstuff_](https://en.wikipedia.org/wiki/Sic_transit_gloria_mundi), so when you link to something from your `.org` (like your link to [this](http://www.wisdomandwonder.com/wordpress/wp-content/uploads/2014/03/C3F.html) at line#=121 of [Sacha.org](https://github.com/sachac/.emacs.d/raw/gh-pages/Sacha.org)), you should
1. First: archive if possible. The [Wayback Machine](http://archive.org/web/) usually WFM, but will occasionally choke due to `robots.txt` on the site to archive.
2. Periodically: remember to check for linkrot. It happens.

**Comment by ebpa** [comment]
I'm sure @sachac will broadly smile at and applaud your recent flurry of enthusiasm!  I agree; your excited perusal of dotemacses is indeed righteous!

However, this sort of ticket sounds quite rude and self-entitled (and probably should avoided here on GitHub).  Instead of pontificating on what practices @sachac "should" be following you might consider reciprocating for the value you have redeemed.  Instead offering "There is at least one dead link in your document.  Please fix it."  You might instead create a useful pull request fixing all broken links.

Or even better: you could write a emacs function to check links in situ and optionally replace them with IA links and then include in your PR: "Hey @sachac!  I wrote [awesome-org-linkrot-checker] and ran it on your dotemacs (which I happen to use because it's awesome!) and noticed there were a couple dead links.  You'll notice that those links are replaced with links to the Internet Archive's Wayback Machine for posterity (that's what [awesome-org-linkrot-checker] does automatically :-D.  If you ever try [awesome-org-linkrot-checker] please let me know what you think!"  And then your function could get included in @sachac's weekly emacs link roundup and then emacsers the world over will start using the tool and linkrot will never be a problem ever again for org-mode users!

Just a thought ;-)

**Comment by sachac** [comment]
Gosh, thanks to both of you for being so helpful! =) I tend to fix linkrot on an as-people-ask-about-stuff basis, following the principle of "you ain't gonna need it" (and the general resourcefulness of people hunting around in my config for ideas). I guess I could proactively fix links that people might never actually click on again, but between my config and my blog, there are way more links than I want to monitor at the moment. =) I fixed that one, though!
